server:
  port: 8081
spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
